name: Build and Deploy
on:
  push:
    branches-ignore:
      - gh-pages
    tags:
      - *

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Build PDF
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          Xvfb -ac -screen scrn 1280x2000x24 :9.0 & export DISPLAY=:9.0 && npx electron-pdf /home/runner/work/curriculum-vitae/curriculum-vitae/dist/index.html /home/runner/work/curriculum-vitae/curriculum-vitae/dist/cv.pdf -e

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/cv.pdf